/**
 * @file    main.c
 * @brief   Variable Switching DC Power Supply — Main Application
 *
 *          STM32F103C8T6 @ 72MHz
 *          Synchronous Buck Converter: 1.25–30V, 0–5A
 *          PID voltage regulation loop at 50µs (TIM1 update ISR)
 *
 *  Peripheral map:
 *   TIM1_CH1/CH1N  PWM hi/lo side → IR2104 gate driver
 *   TIM2_CH1/CH2   Encoder mode  ← EC11 rotary encoder
 *   TIM3_CH4       Fan PWM output → 2N7002 fan driver
 *   ADC1_IN0 (PA0) Voltage sense  ← R-divider (100k/12k)
 *   ADC1_IN1 (PA1) NTC temp sense ← 10kΩ thermistor
 *   I2C1 PB6/PB7   INA226 current sensor + SSD1306 OLED
 *   PA5            Encoder push button
 *   PA8            FAULT GPIO output → IR2104 shutdown
 *   PB0            INA226 ALERT interrupt
 *   PC13/PC14      CV / CC status LEDs
 *   PA9            USART1 TX debug
 *
 * @author  Adnan Anwar Awan
 */

#include "main.h"
#include "pid.h"
#include "adc.h"
#include "display.h"
#include <stdio.h>

/* ── HAL handles (generated by STM32CubeMX) ── */
ADC_HandleTypeDef  hadc1;
I2C_HandleTypeDef  hi2c1;
TIM_HandleTypeDef  htim1;   /* Advanced timer — PWM */
TIM_HandleTypeDef  htim2;   /* Encoder timer */
TIM_HandleTypeDef  htim3;   /* Fan PWM */
UART_HandleTypeDef huart1;  /* Debug UART */

/* ── Application constants ── */
#define SWITCHING_FREQ_HZ   200000U
#define PWM_PERIOD          (72000000U / SWITCHING_FREQ_HZ - 1U)   /* = 359 */
#define DEADTIME_COUNTS     14U       /* 14/72MHz ≈ 194ns dead-time */
#define MAX_DUTY            (PWM_PERIOD - 10U)
#define SOFTSTART_STEPS     100U      /* 100 × 50µs = 5ms ramp */
#define FAN_ON_TEMP_C       50.0f
#define SHUTDOWN_TEMP_C     85.0f
#define V_MIN               1.25f
#define V_MAX               30.0f
#define I_LIMIT_DEFAULT     5.0f

/* ── PID instances ── */
static PID_t vpid;      /* Voltage PID */

/* ── Setpoints ── */
static volatile float v_setpoint = 12.0f;
static volatile float i_limit    = I_LIMIT_DEFAULT;

/* ── Measured values (updated in ISR) ── */
static volatile float v_measured = 0.0f;
static volatile float i_measured = 0.0f;
static volatile float temp_c     = 25.0f;

/* ── Fault flag ── */
static volatile uint8_t fault_active = 0;

/* ── Soft-start counter ── */
static volatile uint32_t ss_count = 0;

/* ── Mode: 0=CV (voltage control), 1=CC (current control) ── */
static volatile uint8_t mode_cc = 0;

/* ── Private function prototypes ── */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_I2C1_Init(void);
static void MX_TIM1_Init(void);
static void MX_TIM2_Init(void);
static void MX_TIM3_Init(void);
static void MX_USART1_Init(void);
static void Fault_Shutdown(const char *reason);
static void Fan_SetDuty(uint8_t percent);
static float INA226_ReadCurrent(void);

/* ─────────────────────────────────────────────────────────────────────────
 * MAIN
 * ───────────────────────────────────────────────────────────────────────── */
int main(void)
{
    HAL_Init();
    SystemClock_Config();

    /* Peripheral initialisation */
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_I2C1_Init();
    MX_TIM1_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();
    MX_USART1_Init();

    /* OLED initialisation */
    Display_Init();
    Display_Clear();

    /* PID initialisation: Kp=0.8, Ki=0.02, Kd=0.001 */
    PID_Init(&vpid, 0.8f, 0.02f, 0.001f, 0.0f, (float)MAX_DUTY, 500.0f);

    /* Start PWM (complementary outputs, dead-time inserted by TIM1) */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_1);

    /* Enable TIM1 update interrupt for PID loop */
    HAL_TIM_Base_Start_IT(&htim1);

    /* Start encoder */
    HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);

    /* Debug banner */
    printf("Variable Switching DC PSU — Adnan Anwar Awan\r\n");
    printf("Vset=%.2fV  Ilim=%.2fA\r\n", v_setpoint, i_limit);

    /* ── Main loop — runs at ~10Hz for display and housekeeping ── */
    uint32_t last_display = 0;
    int32_t  enc_last     = 0;

    while (1)
    {
        /* ── Read encoder for voltage setpoint adjustment ── */
        int32_t enc_now = (int32_t)__HAL_TIM_GET_COUNTER(&htim2);
        int32_t enc_delta = enc_now - enc_last;
        enc_last = enc_now;

        if (enc_delta != 0) {
            v_setpoint += (float)enc_delta * 0.1f;   /* 0.1V per click */
            v_setpoint  = v_setpoint < V_MIN ? V_MIN : (v_setpoint > V_MAX ? V_MAX : v_setpoint);
            ss_count    = 0;   /* Reset soft-start on setpoint change */
            PID_Reset(&vpid);
        }

        /* ── Thermal management ── */
        temp_c = ADC_ReadTemperature();
        if (temp_c >= SHUTDOWN_TEMP_C) {
            Fault_Shutdown("OVER TEMP");
        } else if (temp_c >= FAN_ON_TEMP_C) {
            /* Linear fan speed: 0% at 50°C → 100% at 85°C */
            uint8_t fan_pct = (uint8_t)((temp_c - FAN_ON_TEMP_C) /
                              (SHUTDOWN_TEMP_C - FAN_ON_TEMP_C) * 100.0f);
            Fan_SetDuty(fan_pct);
        } else {
            Fan_SetDuty(0);
        }

        /* ── Update display at 10Hz ── */
        if (HAL_GetTick() - last_display >= 100) {
            last_display = HAL_GetTick();
            float v_out_snap = v_measured;
            float i_out_snap = i_measured;
            Display_Update(v_setpoint, v_out_snap, i_out_snap, mode_cc);

            /* Debug output */
            printf("Vset=%.2f Vout=%.2f Iout=%.2f T=%.1fC %s\r\n",
                   v_setpoint, v_out_snap, i_out_snap, temp_c,
                   mode_cc ? "[CC]" : "[CV]");
        }
    }
}

/* ─────────────────────────────────────────────────────────────────────────
 * TIM1 UPDATE ISR — PID control loop at 50µs
 * ───────────────────────────────────────────────────────────────────────── */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance != TIM1) return;
    if (fault_active)           return;

    /* Read sensors */
    v_measured = ADC_ReadVoltage();
    i_measured = INA226_ReadCurrent();

    /* Over-current protection — switch to CC mode or shut down */
    if (i_measured > i_limit + 0.5f) {
        /* Hard over-current — shutdown */
        Fault_Shutdown("OVER CURRENT");
        return;
    }
    if (i_measured > i_limit) {
        /* Soft CC mode — reduce setpoint to limit current */
        mode_cc = 1;
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_SET);    /* CC LED */
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);  /* CV LED off */
    } else {
        mode_cc = 0;
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);    /* CV LED */
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_RESET);  /* CC LED off */
    }

    /* PID voltage regulation */
    float duty = PID_Update(&vpid, v_setpoint, v_measured);

    /* Soft-start ramp */
    if (ss_count < SOFTSTART_STEPS) {
        duty = duty * (float)ss_count / (float)SOFTSTART_STEPS;
        ss_count++;
    }

    /* Write duty cycle to TIM1 */
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, (uint32_t)duty);
}

/* ─────────────────────────────────────────────────────────────────────────
 * FAULT HANDLER
 * ───────────────────────────────────────────────────────────────────────── */
static void Fault_Shutdown(const char *reason)
{
    fault_active = 1;

    /* Disable PWM immediately */
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, 0);
    HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_1);
    HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_1);

    /* Assert FAULT pin — pulls IR2104 SD low */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, GPIO_PIN_RESET);

    /* FAULT LED on */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, GPIO_PIN_RESET);

    /* Show on display */
    Display_ShowFault(reason);

    /* Log fault */
    printf("FAULT: %s\r\n", reason);
}

/* ─────────────────────────────────────────────────────────────────────────
 * INA226 CURRENT READ (simplified — implement full I2C protocol)
 * ───────────────────────────────────────────────────────────────────────── */
static float INA226_ReadCurrent(void)
{
    uint8_t  buf[2];
    uint16_t raw;
    /* Read shunt voltage register 0x01 */
    uint8_t reg = 0x01;
    HAL_I2C_Master_Transmit(&hi2c1, 0x40 << 1, &reg, 1, 10);
    HAL_I2C_Master_Receive(&hi2c1,  0x40 << 1, buf,  2, 10);
    raw = ((uint16_t)buf[0] << 8) | buf[1];
    /* LSB = 2.5µV, shunt = 10mΩ → I = Vshunt / Rshunt */
    float v_shunt = (int16_t)raw * 2.5e-6f;
    return v_shunt / 0.010f;   /* 10mΩ shunt */
}

/* ─────────────────────────────────────────────────────────────────────────
 * FAN PWM
 * ───────────────────────────────────────────────────────────────────────── */
static void Fan_SetDuty(uint8_t percent)
{
    uint32_t duty = (percent * (__HAL_TIM_GET_AUTORELOAD(&htim3) + 1)) / 100;
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_4, duty);
}

/* ─────────────────────────────────────────────────────────────────────────
 * STUB INIT FUNCTIONS (replace with CubeMX generated code)
 * ───────────────────────────────────────────────────────────────────────── */
static void SystemClock_Config(void) { /* Configure 72MHz from 8MHz HSE */ }
static void MX_GPIO_Init(void)       { /* PA0-PA9, PB0-PB7, PC13-14 */ }
static void MX_ADC1_Init(void)       { /* ADC1, continuous, DMA */ }
static void MX_I2C1_Init(void)       { /* I2C1 400kHz fast-mode */ }
static void MX_TIM2_Init(void)       { /* TIM2 encoder mode CH1+CH2 */ }
static void MX_TIM3_Init(void)       { /* TIM3 CH4 PWM for fan */ }
static void MX_USART1_Init(void)     { /* USART1 115200 8N1 */ }

static void MX_TIM1_Init(void)
{
    /* TIM1 advanced timer — complementary PWM with dead-time
     * Period = 72MHz / 200kHz - 1 = 359
     * Dead-time = 14 counts ≈ 194ns
     */
    htim1.Instance               = TIM1;
    htim1.Init.Prescaler         = 0;
    htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim1.Init.Period            = PWM_PERIOD;
    htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim1.Init.RepetitionCounter = 0;
    HAL_TIM_PWM_Init(&htim1);

    TIM_BreakDeadTimeConfigTypeDef bdt = {0};
    bdt.OffStateRunMode   = TIM_OSSR_ENABLE;
    bdt.OffStateIDLEMode  = TIM_OSSI_ENABLE;
    bdt.LockLevel         = TIM_LOCKLEVEL_OFF;
    bdt.DeadTime          = DEADTIME_COUNTS;
    bdt.BreakState        = TIM_BREAK_DISABLE;
    bdt.AutomaticOutput   = TIM_AUTOMATICOUTPUT_ENABLE;
    HAL_TIMEx_ConfigBreakDeadTime(&htim1, &bdt);
}
